name: Build and Publish WASM version of demo
run-name: ${{ gitea.actor }} is building the WASM version
on:
  push:
    branches:
      - 'main'
      - 'devel'

jobs:
  Build-And-Deploy-main:
    if: github.ref_name == 'main'
    runs-on: archLinux
    steps:
      - run: cd && ./build_and_deploy_jumpartifact.com_demo_0.sh
  Build-And-Deploy-devel:
    if: github.ref_name == 'devel'
    runs-on: archLinux
    steps:
      - run: cd && ./build_and_deploy_jumpartifact.com_demo_0_devel.sh
