name: Build and Publish WASM version of demo
run-name: ${{ gitea.actor }} is building the WASM version
on: [push]

jobs:
  Set-Up-emsdk:
    runs-on: archLinux
    steps:
      - run: cd && ./build_and_deploy_jumpartifact.com_demo_0.sh
